name: Deploy to EC2 using CodeDeploy

on:
  push:
    branches:
      - master2
      - 'releases/**'


jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Zip application
        run: zip -r app.zip . -x '*.git*'

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: springboot-deploy-artifacts-prem
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
          SOURCE_DIR: './'
          DEST_DIR: 'ecommerce-app'

      - name: Deploy to EC2 using CodeDeploy
        uses: webfactory/create-aws-codedeploy-deployment@v1
        with:
          application-name: EcommerceJavaApp
          deployment-group: EcommerceDeploymentGroup
          region: ap-south-1
          bucket: springboot-deploy-artifacts-prem
          bundle: ecommerce-app/app.zip
          wait-until-deployed: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
